services:
    _defaults:
        autowire: true
        public: true

    YesWiki\LoginSso\Controller\:
        resource: 'controllers/*'

    YesWiki\LoginSso\Service\:
        resource: 'services/*'
